### ISSUE TITLE
Maintenance of repo

### ISSUE THREAD

**Issue by Callek** [lovesegfault/beautysh#249]
Hey @hatesegfault @lovesegfault - I notice the beautysh seems to be relatively stalled, its been over 2 years since a formal release, it has a bunch of issues that have not seen any reply or action.

I'm willing to help update and champion this a bit more, as the recently-released python3.12 breaks with this package.

Its particularly painful when trying to run `pre-commit` via Homebrew because it too, is updated to 3.12, but now if we specify this package as part of the lints we have additionally problems.

**Comment by adamryczkowski** [comment]
@Callek  Do you happen to have your private, updated version of the beautysh? Otherwise, we may band together and maintain a working fork; at least until @lovesegfault returns.

**Comment by Callek** [comment]
> @Callek Do you happen to have your private, updated version of the beautysh? Otherwise, we may band together and maintain a working fork; at least until @lovesegfault returns.

I didn't modify beautysh for py3.12, but I did use this in pre-commit

```
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        additional_dependencies:
          - setuptools
```
